/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/bus/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Retrieves a map of each bus to its position */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["BusApiResponse"];
                        "application/json": components["schemas"]["BusApiResponse"];
                        "text/json": components["schemas"]["BusApiResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/buses/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Retrieves a map of each bus to its position */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["BusApiResponse"];
                        "application/json": components["schemas"]["BusApiResponse"];
                        "text/json": components["schemas"]["BusApiResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bus": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Retrieves a map of each bus to its position */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["BusApiResponse"];
                        "application/json": components["schemas"]["BusApiResponse"];
                        "text/json": components["schemas"]["BusApiResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/buses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Retrieves a map of each bus to its position */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["BusApiResponse"];
                        "application/json": components["schemas"]["BusApiResponse"];
                        "text/json": components["schemas"]["BusApiResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bus/info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Retrieves information about a bus */
        get: {
            parameters: {
                query?: {
                    bus?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["BusInfoDto"];
                        "application/json": components["schemas"]["BusInfoDto"];
                        "text/json": components["schemas"]["BusInfoDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/buses/info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Retrieves information about a bus */
        get: {
            parameters: {
                query?: {
                    bus?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["BusInfoDto"];
                        "application/json": components["schemas"]["BusInfoDto"];
                        "text/json": components["schemas"]["BusInfoDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bus/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Retrieves a history of a bus's arrivals */
        get: {
            parameters: {
                query?: {
                    bus?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["BusArrivalDto"][];
                        "application/json": components["schemas"]["BusArrivalDto"][];
                        "text/json": components["schemas"]["BusArrivalDto"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/buses/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Retrieves a history of a bus's arrivals */
        get: {
            parameters: {
                query?: {
                    bus?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["BusArrivalDto"][];
                        "application/json": components["schemas"]["BusArrivalDto"][];
                        "text/json": components["schemas"]["BusArrivalDto"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bus/reports/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Generates a CSV report of all bus arrival data */
        get: {
            parameters: {
                query?: {
                    start?: string;
                    end?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/buses/reports/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Generates a CSV report of all bus arrival data */
        get: {
            parameters: {
                query?: {
                    start?: string;
                    end?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/links": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Retrieves a list of quick links to key BCA services */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["LinkApiResponse"];
                        "application/json": components["schemas"]["LinkApiResponse"];
                        "text/json": components["schemas"]["LinkApiResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/news/stories/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Retrieves the latest news story */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["NewsApiResponseOfNewsStoryDto"];
                        "application/json": components["schemas"]["NewsApiResponseOfNewsStoryDto"];
                        "text/json": components["schemas"]["NewsApiResponseOfNewsStoryDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/news/stories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Retrieves the top 10 latest news stories */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["NewsApiResponseOfIEnumerableOfNewsStoryDto"];
                        "application/json": components["schemas"]["NewsApiResponseOfIEnumerableOfNewsStoryDto"];
                        "text/json": components["schemas"]["NewsApiResponseOfIEnumerableOfNewsStoryDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/news/stories/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Retrieves a story by its ID */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["NewsStoryDto2"];
                        "application/json": components["schemas"]["NewsStoryDto2"];
                        "text/json": components["schemas"]["NewsStoryDto2"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lunch/week": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Retrieves the lunch menu for the week */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["NutrisliceApiResponseOfMenuWeekDto"];
                        "application/json": components["schemas"]["NutrisliceApiResponseOfMenuWeekDto"];
                        "text/json": components["schemas"]["NutrisliceApiResponseOfMenuWeekDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lunch/day": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Retrieves the lunch menu for the day */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["NutrisliceApiResponseOfMenuDayDto"];
                        "application/json": components["schemas"]["NutrisliceApiResponseOfMenuDayDto"];
                        "text/json": components["schemas"]["NutrisliceApiResponseOfMenuDayDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/schedules/{date}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Retrieves details of the schedule for a day */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    date: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ScheduleDayDto"];
                        "application/json": components["schemas"]["ScheduleDayDto"];
                        "text/json": components["schemas"]["ScheduleDayDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        BusApiResponse: {
            /** Format: int32 */
            count: number;
            data: {
                [key: string]: string;
            };
            /** Format: date-time */
            expiry: string | null;
        };
        BusArrivalDto: {
            busName: string | null;
            busPosition: string | null;
            /** Format: date-time */
            arrivalTime: string;
        };
        BusCompanyDto: {
            name: string;
        } | null;
        BusInfoDto: {
            name: string;
            company: components["schemas"]["BusCompanyDto"];
        };
        FoodItemDto: {
            /** Format: int32 */
            id: number;
            name: string | null;
            description: string | null;
            subtext: string | null;
            imageUrl: string | null;
            nutritionInfo: components["schemas"]["FoodItemNutritionInfoDto"];
        };
        FoodItemNutritionInfoDto: {
            /** Format: double */
            calories: number | null;
            /** Format: double */
            fat: number | null;
            /** Format: double */
            saturatedFat: number | null;
            /** Format: double */
            transFat: number | null;
            /** Format: double */
            cholesterol: number | null;
            /** Format: double */
            carbs: number | null;
            /** Format: double */
            addedSugar: number | null;
            /** Format: double */
            sugar: number | null;
            /** Format: double */
            potassium: number | null;
            /** Format: double */
            sodium: number | null;
            /** Format: double */
            fiber: number | null;
            /** Format: double */
            protein: number | null;
            /** Format: double */
            iron: number | null;
            /** Format: double */
            calcium: number | null;
            /** Format: double */
            vitaminC: number | null;
            /** Format: double */
            vitaminA: number | null;
            /** Format: double */
            retinolEquivalents: number | null;
            /** Format: double */
            microgramsVitaminA: number | null;
            /** Format: double */
            vitaminD: number | null;
            /** Format: double */
            microgramsVitaminD: number | null;
        } | null;
        LinkApiResponse: {
            /** Format: int32 */
            count: number;
            data: components["schemas"]["LinkDto"][];
        };
        LinkDto: {
            name: string;
            /** Format: uri */
            target: string;
        };
        MenuDayDto: {
            date: string | null;
            menuItems: components["schemas"]["MenuItemDto"][];
        };
        MenuDayDto2: {
            date: string | null;
            menuItems: components["schemas"]["MenuItemDto"][];
        } | null;
        MenuItemDto: {
            /** Format: date-time */
            date: string | null;
            /** Format: int32 */
            position: number;
            isSectionTitle: boolean;
            text: string | null;
            food: components["schemas"]["FoodItemDto"];
            /** Format: uint32 */
            stationID: number;
            isStationHeader: boolean;
            image: string | null;
            category: string | null;
        };
        MenuWeekDto: {
            startDate: string | null;
            displayName: string | null;
            days: components["schemas"]["MenuDayDto"][];
        } | null;
        NewsApiResponseOfIEnumerableOfNewsStoryDto: {
            data: components["schemas"]["NewsStoryDto2"][] | null;
            /** Format: date-time */
            expiry: string | null;
        };
        NewsApiResponseOfNewsStoryDto: {
            data: components["schemas"]["NewsStoryDto"];
            /** Format: date-time */
            expiry: string | null;
        };
        NewsStoryDto: {
            /** Format: int32 */
            id: number;
            title: string;
            link: string;
            imageLink: string | null;
            contentHtml: string | null;
            /** Format: date-time */
            createdAt: string;
        } | null;
        NewsStoryDto2: {
            /** Format: int32 */
            id: number;
            title: string;
            link: string;
            imageLink: string | null;
            contentHtml: string | null;
            /** Format: date-time */
            createdAt: string;
        };
        NutrisliceApiResponseOfMenuDayDto: {
            data: components["schemas"]["MenuDayDto2"];
            /** Format: date-time */
            expiry: string | null;
        };
        NutrisliceApiResponseOfMenuWeekDto: {
            data: components["schemas"]["MenuWeekDto"];
            /** Format: date-time */
            expiry: string | null;
        };
        ScheduleDayDto: {
            /** Format: int32 */
            id: number;
            /** Format: date */
            day: string;
            /** Format: int32 */
            scheduleId: number;
            schedule: components["schemas"]["ScheduleDto"];
        };
        ScheduleDto: {
            /** Format: int32 */
            id: number;
            name: string;
            items: components["schemas"]["ScheduleItemDto"][];
        } | null;
        ScheduleItemDto: {
            periodName: string;
            /** Format: time */
            startTime: string;
            /** Format: time */
            endTime: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
